### ISSUE TITLE
Probar alternativas en el manejo de transacciones

### ISSUE THREAD

**Issue by MarianoSalerno** [Amitors/PdP2018#1]
Plantear las transacciones como funciones y compararlo contra la solucuion que tienen actualmente para ver cual se ajusta mejor a la siguiente entrega

**Comment by MarianoSalerno** [comment]
Cuando hagan esto traten de no repetir codigo en todos los lugares donde validan que el nombre del usuario al que se le aplica la transaccion sea el correcto

**Comment by sanuzzi** [comment]
Pueden cerrar este issue (no puedo porque no lo creé y no soy colaborador en este proyecto)
