### ISSUE TITLE
Explicación de consultas existenciales e individuales

### ISSUE THREAD

**Issue by sanuzzi** [Amitors/PdP2018#17]
No queda claro en la parte individual, qué individuos usarían. Pareciera que dice casi lo mismo que lo de arriba.

Expliquen de forma más concisa, y den ejemplos puntuales de cada cosa. Jueguen también con cuándo usar variables anónimas y cuándo no, y qué significa cada consulta.

Esto aplica en ambos casos en donde había que hablar de este tema. Sean más claros y den ejemplos de lo que vayan diciendo.

**Comment by MarianoSalerno** [comment]
Corregido
